### ISSUE TITLE
Question: Is it possible to match patterns in the event stream?

### ISSUE THREAD

**Issue by timidak** [RxCEP/cepjs#7]
Hi first of all cool lib! 

I want to use this library for some research work. Now I'm wonder if it is possible to do pattern matching over an event stream and how? 😄 

I want to match patterns like `a -> b -> c` where each letter is an event. If these events follow the pattern should be detected and a callback should then be executed. Is this possible now? Do you have a documentation or examples where I can find more detailed information?

Thanks!

**Comment by carloszimm** [comment]
Hi @timidak!
Thanks for the complements and sorry for taking so long (I've been busy with other projects and your issue passed unnoticed). Please, reopen the issue if you are still interested.
So, by `->`, did you imply any temporal correlation or the order doesn't matter?

1) If the former, there's currently no support or operator for such. Actually, it's among some of the patterns still unimplemented (aka sequence). As noted in the [contributing](https://github.com/RxCEP/cepjs/blob/master/CONTRIBUTING.md) section, the majority of the operators have been taken from the book Event Processing in Action[1]. Within the chapter 9, you may find all the operations that we planned to implement in the project. Actually, this project has been the subject two researches [2] and [3]; [3] contains more updated information about the project including the operators already implemented.

2) If the latter, maybe the `all` operator could be used. It relies on a set of event type ids that you pass to the operator. In its most basic use, you could "call it" like `all(['a', 'b', 'c'], 'event detected')` where 'a', 'b' and 'c' are the event type ids and 'event detected' is the id of the newly generated event.

All the syntax has been based on the RxJS's syntax and a basic example can also be found in [3]. There is no current documentation as I've been working most time in this project only by myself; thus, it is one of the pending tasks. We gladly accept any contribution that could improve the project/code or help with those pending tasks :)

PS: I filled the code with comments to make easy for anyone who want to contribute or even just understand some operations. Thus, if you access the [logical](https://github.com/RxCEP/cepjs/blob/master/packages/cepjs-core/lib/reactive-libs/rxjs/adapter/patterns/logical.js) file in the patterns folder (RxJS adapter), you can see those comments and possibly a more descriptive explanation of the logical operators for instance.

Best,
Carlos

Sources
[1] Etzion, O., & Niblett, P. (2010). Event processing in action. Manning Publications Co..
[2] Zimmerle, C., & Gama, K. (2018, October). Reactive CEP: Integrating Complex Event Processing into Web Reactive Languages. In Proceedings of the 24th Brazilian Symposium on Multimedia and the Web (pp. 69-72).
[3] Zimmerle, C., Oliveira, W., Gama, K., & Castor, F. (2019, September). Reactive-based complex event processing: An overview and energy consumption analysis of cep. js. In Proceedings of the XXXIII Brazilian Symposium on Software Engineering (pp. 84-93).
